'use client';

import { useEffect } from 'react';
import { useFormState, useFormStatus } from 'react-dom';
import { generatePathwayAction } from '@/lib/actions';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending}>
      {pending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
      Generate Pathway
    </Button>
  );
}

export default function LearningPathway({ domain }: { domain: string }) {
  const initialState = { data: null, error: null };
  const [state, dispatch] = useFormState(generatePathwayAction, initialState);
  const { toast } = useToast();

  useEffect(() => {
    if (state.error) {
      toast({
        variant: 'destructive',
        title: 'Error',
        description: state.error,
      });
    }
  }, [state.error, toast]);

  const parsedPathway = state.data?.learningPathway
    .split(/\n\n(?=Stage|### |## )/g)
    .map((part, index) => {
      const lines = part.trim().split('\n');
      const title = lines[0].replace(/Stage \d: |### |## /g, '').trim();
      const content = lines.slice(1).join('\n').trim();
      return { id: `item-${index + 1}`, title, content };
    });

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <Card className="lg:col-span-1">
        <form action={dispatch}>
          <CardHeader>
            <CardTitle>Learning Pathway Generator</CardTitle>
            <CardDescription>
              Describe your skills, preferences, and goals to generate a custom learning plan.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <input type="hidden" name="domain" value={domain} />
            <div className="space-y-2">
              <Label htmlFor="skills">Current Skills</Label>
              <Textarea
                id="skills"
                name="skills"
                placeholder="e.g., Basic Python, HTML/CSS"
                required
                rows={3}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="preferences">Learning Preferences</Label>
              <Textarea
                id="preferences"
                name="preferences"
                placeholder="e.g., Project-based learning, visual examples"
                required
                rows={3}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="goals">Learning Goals</Label>
              <Textarea
                id="goals"
                name="goals"
                placeholder="e.g., Become a full-stack developer in 6 months"
                required
                rows={3}
              />
            </div>
          </CardContent>
          <CardFooter>
            <SubmitButton />
          </CardFooter>
        </form>
      </Card>

      <Card className="lg:col-span-2">
        <CardHeader>
          <CardTitle>Your Personalized Pathway</CardTitle>
          <CardDescription>
            Here is the step-by-step curriculum generated by the AI based on your input.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {state.data?.learningPathway ? (
            <Accordion type="single" collapsible className="w-full">
              {parsedPathway?.map(item => (
                <AccordionItem value={item.id} key={item.id}>
                  <AccordionTrigger>{item.title}</AccordionTrigger>
                  <AccordionContent>
                    <div className="prose prose-sm max-w-none dark:prose-invert" dangerouslySetInnerHTML={{ __html: item.content.replace(/\n/g, '<br />') }} />
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          ) : (
            <div className="text-center text-muted-foreground py-12">
              Your generated learning pathway will appear here.
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
